# CMake generated Testfile for 
# Source directory: /home/stas/source/ns-3.37/src/tap-bridge/examples
# Build directory: /home/stas/source/ns-3.37/cmake-cache/src/tap-bridge/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-tap-csma "ns3.37-tap-csma-debug")
set_tests_properties(ctest-tap-csma PROPERTIES  WORKING_DIRECTORY "/home/stas/source/ns-3.37/build/src/tap-bridge/examples/" _BACKTRACE_TRIPLES "/home/stas/source/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/home/stas/source/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/stas/source/ns-3.37/build-support/custom-modules/ns3-module-macros.cmake;388;build_exec;/home/stas/source/ns-3.37/src/tap-bridge/examples/CMakeLists.txt;2;build_lib_example;/home/stas/source/ns-3.37/src/tap-bridge/examples/CMakeLists.txt;0;")
add_test(ctest-tap-csma-virtual-machine "ns3.37-tap-csma-virtual-machine-debug")
set_tests_properties(ctest-tap-csma-virtual-machine PROPERTIES  WORKING_DIRECTORY "/home/stas/source/ns-3.37/build/src/tap-bridge/examples/" _BACKTRACE_TRIPLES "/home/stas/source/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/home/stas/source/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/stas/source/ns-3.37/build-support/custom-modules/ns3-module-macros.cmake;388;build_exec;/home/stas/source/ns-3.37/src/tap-bridge/examples/CMakeLists.txt;12;build_lib_example;/home/stas/source/ns-3.37/src/tap-bridge/examples/CMakeLists.txt;0;")
add_test(ctest-tap-wifi-virtual-machine "ns3.37-tap-wifi-virtual-machine-debug")
set_tests_properties(ctest-tap-wifi-virtual-machine PROPERTIES  WORKING_DIRECTORY "/home/stas/source/ns-3.37/build/src/tap-bridge/examples/" _BACKTRACE_TRIPLES "/home/stas/source/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/home/stas/source/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/stas/source/ns-3.37/build-support/custom-modules/ns3-module-macros.cmake;388;build_exec;/home/stas/source/ns-3.37/src/tap-bridge/examples/CMakeLists.txt;21;build_lib_example;/home/stas/source/ns-3.37/src/tap-bridge/examples/CMakeLists.txt;0;")
add_test(ctest-tap-wifi-dumbbell "ns3.37-tap-wifi-dumbbell-debug")
set_tests_properties(ctest-tap-wifi-dumbbell PROPERTIES  WORKING_DIRECTORY "/home/stas/source/ns-3.37/build/src/tap-bridge/examples/" _BACKTRACE_TRIPLES "/home/stas/source/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/home/stas/source/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/stas/source/ns-3.37/build-support/custom-modules/ns3-module-macros.cmake;388;build_exec;/home/stas/source/ns-3.37/src/tap-bridge/examples/CMakeLists.txt;32;build_lib_example;/home/stas/source/ns-3.37/src/tap-bridge/examples/CMakeLists.txt;0;")
