# CMake generated Testfile for 
# Source directory: /home/stas/source/ns-3.37/scratch
# Build directory: /home/stas/source/ns-3.37/cmake-cache/scratch
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-scratch_FDBET "ns3.37-FDBET-debug")
set_tests_properties(ctest-scratch_FDBET PROPERTIES  WORKING_DIRECTORY "/home/stas/source/ns-3.37/build/scratch/" _BACKTRACE_TRIPLES "/home/stas/source/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/home/stas/source/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/stas/source/ns-3.37/scratch/CMakeLists.txt;47;build_exec;/home/stas/source/ns-3.37/scratch/CMakeLists.txt;59;create_scratch;/home/stas/source/ns-3.37/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_LTE_1 "ns3.37-LTE_1-debug")
set_tests_properties(ctest-scratch_LTE_1 PROPERTIES  WORKING_DIRECTORY "/home/stas/source/ns-3.37/build/scratch/" _BACKTRACE_TRIPLES "/home/stas/source/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/home/stas/source/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/stas/source/ns-3.37/scratch/CMakeLists.txt;47;build_exec;/home/stas/source/ns-3.37/scratch/CMakeLists.txt;59;create_scratch;/home/stas/source/ns-3.37/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_RobinRobin "ns3.37-RobinRobin-debug")
set_tests_properties(ctest-scratch_RobinRobin PROPERTIES  WORKING_DIRECTORY "/home/stas/source/ns-3.37/build/scratch/" _BACKTRACE_TRIPLES "/home/stas/source/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/home/stas/source/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/stas/source/ns-3.37/scratch/CMakeLists.txt;47;build_exec;/home/stas/source/ns-3.37/scratch/CMakeLists.txt;59;create_scratch;/home/stas/source/ns-3.37/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_TDBET "ns3.37-TDBET-debug")
set_tests_properties(ctest-scratch_TDBET PROPERTIES  WORKING_DIRECTORY "/home/stas/source/ns-3.37/build/scratch/" _BACKTRACE_TRIPLES "/home/stas/source/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/home/stas/source/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/stas/source/ns-3.37/scratch/CMakeLists.txt;47;build_exec;/home/stas/source/ns-3.37/scratch/CMakeLists.txt;59;create_scratch;/home/stas/source/ns-3.37/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_first "ns3.37-first-debug")
set_tests_properties(ctest-scratch_first PROPERTIES  WORKING_DIRECTORY "/home/stas/source/ns-3.37/build/scratch/" _BACKTRACE_TRIPLES "/home/stas/source/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/home/stas/source/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/stas/source/ns-3.37/scratch/CMakeLists.txt;47;build_exec;/home/stas/source/ns-3.37/scratch/CMakeLists.txt;59;create_scratch;/home/stas/source/ns-3.37/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_plot_parser "ns3.37-plot_parser-debug")
set_tests_properties(ctest-scratch_plot_parser PROPERTIES  WORKING_DIRECTORY "/home/stas/source/ns-3.37/build/scratch/" _BACKTRACE_TRIPLES "/home/stas/source/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/home/stas/source/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/stas/source/ns-3.37/scratch/CMakeLists.txt;47;build_exec;/home/stas/source/ns-3.37/scratch/CMakeLists.txt;59;create_scratch;/home/stas/source/ns-3.37/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_rlc_mod "ns3.37-rlc_mod-debug")
set_tests_properties(ctest-scratch_rlc_mod PROPERTIES  WORKING_DIRECTORY "/home/stas/source/ns-3.37/build/scratch/" _BACKTRACE_TRIPLES "/home/stas/source/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/home/stas/source/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/stas/source/ns-3.37/scratch/CMakeLists.txt;47;build_exec;/home/stas/source/ns-3.37/scratch/CMakeLists.txt;59;create_scratch;/home/stas/source/ns-3.37/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_rlc_speed_mod "ns3.37-rlc_speed_mod-debug")
set_tests_properties(ctest-scratch_rlc_speed_mod PROPERTIES  WORKING_DIRECTORY "/home/stas/source/ns-3.37/build/scratch/" _BACKTRACE_TRIPLES "/home/stas/source/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/home/stas/source/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/stas/source/ns-3.37/scratch/CMakeLists.txt;47;build_exec;/home/stas/source/ns-3.37/scratch/CMakeLists.txt;59;create_scratch;/home/stas/source/ns-3.37/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_scratch-simulator "ns3.37-scratch-simulator-debug")
set_tests_properties(ctest-scratch_scratch-simulator PROPERTIES  WORKING_DIRECTORY "/home/stas/source/ns-3.37/build/scratch/" _BACKTRACE_TRIPLES "/home/stas/source/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/home/stas/source/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/stas/source/ns-3.37/scratch/CMakeLists.txt;47;build_exec;/home/stas/source/ns-3.37/scratch/CMakeLists.txt;59;create_scratch;/home/stas/source/ns-3.37/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_second "ns3.37-second-debug")
set_tests_properties(ctest-scratch_second PROPERTIES  WORKING_DIRECTORY "/home/stas/source/ns-3.37/build/scratch/" _BACKTRACE_TRIPLES "/home/stas/source/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/home/stas/source/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/stas/source/ns-3.37/scratch/CMakeLists.txt;47;build_exec;/home/stas/source/ns-3.37/scratch/CMakeLists.txt;59;create_scratch;/home/stas/source/ns-3.37/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_subdir_scratch-subdir "ns3.37-scratch-subdir-debug")
set_tests_properties(ctest-scratch_subdir_scratch-subdir PROPERTIES  WORKING_DIRECTORY "/home/stas/source/ns-3.37/build/scratch/subdir/" _BACKTRACE_TRIPLES "/home/stas/source/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/home/stas/source/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/stas/source/ns-3.37/scratch/CMakeLists.txt;47;build_exec;/home/stas/source/ns-3.37/scratch/CMakeLists.txt;89;create_scratch;/home/stas/source/ns-3.37/scratch/CMakeLists.txt;0;")
